# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 03:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(verbose_name='评论')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('articleid', models.IntegerField(default=0, verbose_name='文章ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djblog.Article', verbose_name='所属文章')),
            ],
        ),
    ]
