# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloger',
            name='slist',
            field=models.ManyToManyField(blank=True, null=True, related_name='likelist', to='djblog.Bloger', verbose_name='关注列表'),
        ),
        migrations.AddField(
            model_name='bloger',
            name='tlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='blacklist', to='djblog.Bloger', verbose_name='拉黑列表'),
        ),
    ]
